# Input/output configuration
input_dir: $CFS/m3443/usr/daniel/dataset/embedding 
output_dir: $CFS/m3443/usr/daniel/dataset/filter
project: LRT_Filter
filter_cut: 0.05
overwrite: True

# Dataset parameters
pt_background_min: 0.0
pt_signal_min: 0.0
datatype_names: [[train, val, test]] # Which directory prefixes to use, assuming at least a train dataset 
datatype_split: [[900, 50, 50]] # Number of [training, validation, testing] examples
endcaps: True
true_edges: layerless_true_edges
noise: True

# Model parameters
in_channels: 3
hidden: 512
nb_layer: 5
emb_channels: 0
batch_size: 1
layernorm: True
batchnorm: False
n_chunks: 2
edges_per_batch: 500000
ratio: 2
weight: 2
warmup: 200
lr: 0.000001
factor: 0.3
patience: 20
regime: [[non-ci, non-ci]] # probably should add PID into the regime
max_epochs: 100

# Post-processing
callbacks: [FilterInferenceCallback, FilterGetPurEff]
checkpoint_path: lightning_checkpoints
