evtid:
  range: [
    0, 9999
  ]

event:
  files:
    gnn_processed:
      file: "v5/gnn_processed_0.3_900/test/{evtid:04}"
      parser: pyg.pickle

    particles:
      file: "v5/particles/event{evtid:09}-particles.csv"
      parser: pandas.csv

  data:
    hits:
      gnn_processed:
        hit_id: hid
        particle_id: pid

    particles:
      particles:
        particle_id: particle_id
        particle_type: particle_type
        charge: q
        # Parent information.
        parent_ptype: parent_pid
        # Production vertex.
        vx: vx
        vy: vy
        vz: vz
        # Momentum.
        px: px
        py: py
        pz: pz

    edges:
      gnn_processed:
        sender:
          tag: edge_index
          processing:
            - select: { row: 0 }
        receiver:
          tag: edge_index
          processing:
            - select: { row: 1 }
        truth: truth
        score: score
