rm -r /global/cfs/cdirs/m3443/usr/daniel/dataset/embedding_1/*
rm -r /global/cfs/cdirs/m3443/usr/daniel/dataset/filter_1/*
rm -r /global/cfs/cdirs/m3443/usr/daniel/dataset/gnn_1/*
rm -r /global/cfs/cdirs/m3443/usr/daniel/dataset/embedding_2/*
rm -r /global/cfs/cdirs/m3443/usr/daniel/dataset/filter_2/*
rm -r /global/cfs/cdirs/m3443/usr/daniel/dataset/gnn_2/*
rm -r /global/cfs/cdirs/m3443/usr/daniel/dataset/embedding_3/*
rm -r /global/cfs/cdirs/m3443/usr/daniel/dataset/filter_3/*
rm -r /global/cfs/cdirs/m3443/usr/daniel/dataset/gnn_3/*
