# Input/output configuration
# input_dir: /media/daniel0321/LargeFiles/datasets/TrackML/TTbar_Pt1GeV_PU40_5000Events/
input_dir: $CFS/m3443/usr/daniel/raw_dataset/HNL_output_noPU_npz
output_dir: $CFS/m3443/usr/daniel/dataset/embedding_1
project: LRT_Embedding
overwrite: True

# Dataset parameters
pt_signal_min: 0
pt_background_min: 0
train_split: [[900, 100, 500]] # Number of [training, validation, testing] examples
true_edges: layerless_true_edges
noise: True # True

# Model parameters
in_channels: 3
emb_hidden: 1024
nb_layer: 4
emb_dim: 12
weight: 4
randomisation: 2
batch_size: 1
points_per_batch: 130000
r_train: 0.2 # 1.6
r_val: 0.2 # 1.6
r_test: 0.2 # 1.6
knn: 200 # 20
warmup: 4
margin: 0.2
lr: 0.0001
factor: 0.58
patience: 19
regime: [[rp, hnm, norm]]
max_epochs: 30 # 30

# Inference
checkpoint_path: lightning_checkpoints

# Postprocessing
callbacks: [EmbeddingPurEff, EmbeddingBuilder]  
