batch_size: 1
callbacks:
- EmbeddingPurEff
- EmbeddingBuilder
checkpoint_path: lightning_checkpoints
emb_dim: 12
emb_hidden: 1024
factor: 0.58
in_channels: 3
input_dir: $CFS/m3443/usr/daniel/raw_dataset/HNL_output_noPU_npz
knn: 200
log_dir: logging/version_1
lr: 0.0001
margin: 0.2
max_epochs: 30
nb_layer: 4
noise: true
output_dir: $CFS/m3443/usr/daniel/dataset/embedding_1
overwrite: true
patience: 19
performance_path: stage_1.yaml
points_per_batch: 130000
project: LRT_Embedding
pt_background_min: 0
pt_signal_min: 0
r_test: 0.2
r_train: 0.2
r_val: 0.2
randomisation: 2
regime:
- - rp
  - hnm
  - norm
train_split:
- - 4000
  - 500
  - 500
true_edges: layerless_true_edges
warmup: 4
weight: 4
