stage_list:
- batch_config: configs/batch_gpu_default.yaml
  batch_setup: true
  config: train_2.yaml
  name: LayerlessEmbedding
  set: Embedding
- batch_config: configs/batch_gpu_default.yaml
  batch_setup: true
  config: train_2.yaml
  name: VanillaFilter
  set: Filter
- batch_config: configs/batch_gpu_default.yaml
  batch_setup: true
  config: train_2.yaml
  name: ResAGNN
  set: GNN
