evtid:
  range: [0, 5000]

gnn_arch:
  list:
    - ResAGNN+ReLU

HNL:
  list:
    - 15GeV200mm

event:
  files:
    gnn_processed:
      # file: "../sample_data/test/{evtid:04}" 
      file: "/global/cfs/cdirs/m3443/usr/daniel/dataset/gnn_3/test/{evtid:04}"
      parser: pyg.pickle

    particles:
      # file: "../sample_data/raw_data_sample/event{evtid:09}-particles.csv"
      file: "/global/cfs/cdirs/m3443/usr/daniel/raw_dataset/raw_HNL_noPU/event{evtid:09}-particles.csv"
      parser: pandas.csv

  data:
    hits:
      gnn_processed:
        hit_id: hid
        particle_id: pid

    particles:
      particles:
        particle_id: particle_id
        # particle_type: particle_type
        charge: q
        # Parent information.
        # parent_ptype: parent_pid
        # Production vertex.
        vx: vx
        vy: vy
        vz: vz
        # Momentum.
        px: px
        py: py
        pz: pz

    edges:
      gnn_processed:
        sender:
          tag: edge_index
          processing:
            - select: { row: 0 }
        receiver:
          tag: edge_index
          processing:
            - select: { row: 1 }
        truth: truth
        score: score
