# Input/output configuration
input_dir: $CFS/m3443/usr/daniel/dataset/embedding_3
output_dir: $CFS/m3443/usr/daniel/dataset/filter_3
performance_path: stage_3.yaml
log_dir: logging/version_3
project: LRT_Filter
filter_cut: 0.01 # 0.05
overwrite: True

# Dataset parameters
pt_background_min: 0.0
pt_signal_min: 0.0
datatype_names: [[train, val, test]] # Which directory prefixes to use, assuming at least a train dataset 
datatype_split: [[900, 100, 500]] # Number of [training, validation, testing] examples
endcaps: True
true_edges: layerless_true_edges
noise: True

# Model parameters
in_channels: 3
hidden: 512
nb_layer: 8
emb_channels: 0
batch_size: 1
layernorm: True
batchnorm: False
n_chunks: 4
edges_per_batch: 300000
ratio: 2
weight: 1
warmup: 800
lr: 0.001
factor: 0.4
patience: 9
regime: [[]] # probably should add PID into the regime
max_epochs: 20 # 20

# Post-processing
callbacks: [FilterInferenceCallback, FilterGetPurEff]
checkpoint_path: lightning_checkpoints
