batch_size: 1
batchnorm: false
callbacks:
- FilterInferenceCallback
- FilterGetPurEff
checkpoint_path: $CFS/m3443/usr/daniel/lightning_checkpoints
datatype_names:
- - train
  - val
  - test
datatype_split:
- - 2000
  - 500
  - 500
edges_per_batch: 300000
emb_channels: 0
endcaps: true
factor: 0.4
filter_cut: 0.01
hidden: 512
in_channels: 3
input_dir: $CFS/m3443/usr/daniel/dataset/embedding_2
layernorm: true
log_dir: logging/version_2
lr: 0.001
max_epochs: 20
n_chunks: 4
nb_layer: 8
noise: true
output_dir: $CFS/m3443/usr/daniel/dataset/filter_2
overwrite: true
patience: 9
performance_path: stage_2.yaml
project: LRT_Filter
pt_background_min: 0.0
pt_signal_min: 0.0
ratio: 2
regime:
- []
true_edges: layerless_true_edges
warmup: 800
weight: 1
