embedding:
  input_dir: $CFS/m3443/usr/daniel/raw_dataset/HNL_output_noPU_npz
  output_dir: $CFS/m3443/usr/daniel/dataset/embedding_1
  performance_path: stage_1.yaml
  log_dir: logging/version_1
  project: LRT_Embedding
  overwrite: True

  # Dataset parameters
  pt_signal_min: 0
  pt_background_min: 0
  train_split: [[20, 10, 10]] # Number of [training, validation, testing] examples
  true_edges: layerless_true_edges
  noise: True # True

  # Model parameters
  in_channels: 3
  emb_hidden: 1024
  nb_layer: 4
  emb_dim: 12
  weight: 4
  randomisation: 2
  batch_size: 1
  points_per_batch: 130000
  r_train: 0.2 # 1.6
  r_val: 0.2 # 1.6
  r_test: 0.2 # 1.6
  knn: 200 # 20
  warmup: 4
  margin: 0.2
  lr: 0.0001
  factor: 0.58
  patience: 19
  regime: [[rp, hnm, norm]]
  max_epochs: 1 # 30

  # Inference
  checkpoint_path: lightning_checkpoints

  # Postprocessing
  callbacks: [EmbeddingPurEff, EmbeddingBuilder]

filter:
  # Input/output configuration
  input_dir: $CFS/m3443/usr/daniel/dataset/embedding_1 
  output_dir: $CFS/m3443/usr/daniel/dataset/filter_1
  performance_path: stage_1.yaml
  log_dir: logging/version_1
  project: LRT_Filter
  filter_cut: 0.01 # 0.05
  overwrite: True

  # Dataset parameters
  pt_background_min: 0.0
  pt_signal_min: 0.0
  datatype_names: [[train, val, test]] # Which directory prefixes to use, assuming at least a train dataset 
  datatype_split: [[20, 10, 10]] # Number of [training, validation, testing] examples
  endcaps: True
  true_edges: layerless_true_edges
  noise: True

  # Model parameters
  in_channels: 3
  hidden: 512
  nb_layer: 8
  emb_channels: 0
  batch_size: 1
  layernorm: True
  batchnorm: False
  n_chunks: 4
  edges_per_batch: 300000
  ratio: 2
  weight: 1
  warmup: 800
  lr: 0.001
  factor: 0.4
  patience: 9
  regime: [[]] # probably should add PID into the regime
  max_epochs: 20 # 20

  # Post-processing
  callbacks: [FilterInferenceCallback, FilterGetPurEff]
  checkpoint_path: lightning_checkpoints

gnn:
  # Input/output configuration
  input_dir: $CFS/m3443/usr/daniel/dataset/filter_1
  output_dir: $CFS/m3443/usr/daniel/dataset/gnn_1
  performance_path: stage_1.yaml
  log_dir: logging/version_1
  project: LRT_GNN
  edge_cut: 0.5 # 0.5
  overwrite: True

  # Dataset parameters
  pt_background_min: 0.0
  pt_signal_min: 0.0
  datatype_names: [[train, val, test]] # Which directory prefixes to use, assuming at least a train dataset 
  datatype_split: [[20, 10, 10]] # Number of [training, validation, testing] examples
  endcaps: True
  true_edges: layerless_true_edges
  noise: True

  # Model parameters
  in_channels: 3
  hidden: 256
  batch_size: 1
  n_graph_iters: 8
  nb_node_layer: 5
  nb_edge_layer: 8 # 3
  emb_channels: 0
  layernorm: True
  hidden_activation: ReLU
  weight: 2
  delta_eta: 1.2
  warmup: 200
  lr: 0.001
  factor: 0.3
  patience: 10
  regime: [[]]
  max_epochs: 25 # 25
  slack_alert: False

  checkpoint_path: lightning_checkpoints

  # Post-processing
  callbacks: [GNNEffPur, GNNBuilder]
