track_building_configs:
  input_dir: ../dataset/GNN/
  score_cut: 0.9
  output_dir: ../dataset/tracking/label

evaluation_configs:
  output_dir: ../dataset/tracking/track
  min_pt: 1
  max_eta: 4
  min_track_length: 3
  min_particle_length: 3
  matching_fraction: 0.5
  matching_style: ATLAS
