evtid:
  range: [0, 10000]

gnn_arch:
  list:
    - ResAGNN+ReLU

HNL:
  list:
    - 15GeV200mm

event:
  files:
    gnn_processed:
      file: "test/0143"
      parser: pyg.pickle

    particles:
      file: "train_100_events/event000001000-particles.csv"
      parser: pandas.csv

  data:
    hits:
      gnn_processed:
        hit_id: hid
        particle_id: pid

    particles:
      particles:
        particle_id: particle_id
        # particle_type: particle_type
        charge: q
        # Parent information.
        # parent_ptype: parent_pid
        # Production vertex.
        vx: vx
        vy: vy
        vz: vz
        # Momentum.
        px: px
        py: py
        pz: pz

    edges:
      gnn_processed:
        sender:
          tag: edge_index
          processing:
            - select: { row: 0 }
        receiver:
          tag: edge_index
          processing:
            - select: { row: 1 }
        truth: truth
        score: score
