# Input/output configuration
input_dir: $CFS/m3443/usr/daniel/dataset/filter_2
output_dir: $CFS/m3443/usr/daniel/dataset/gnn_2
project: LRT_GNN
edge_cut: 0.5 # 0.5
overwrite: True

# Dataset parameters
pt_background_min: 0.0
pt_signal_min: 0.0
datatype_names: [[train, val, test]] # Which directory prefixes to use, assuming at least a train dataset 
datatype_split: [[900, 100, 500]] # Number of [training, validation, testing] examples
endcaps: True
true_edges: layerless_true_edges
noise: True

# Model parameters
in_channels: 3
hidden: 1024
batch_size: 1
n_graph_iters: 8
nb_node_layer: 5
nb_edge_layer: 8 # 3
emb_channels: 0
layernorm: True
hidden_activation: ReLU
weight: 2
delta_eta: 1.2
warmup: 200
lr: 0.001
factor: 0.3
patience: 10
regime: [[]]
max_epochs: 25 # 25
slack_alert: False

checkpoint_path: lightning_checkpoints

# Post-processing
callbacks: [GNNEffPur, GNNBuilder]