batch_size: 1
callbacks:
- GNNEffPur
- GNNBuilder
checkpoint_path: $CFS/m3443/usr/daniel/lightning_checkpoints
datatype_names:
- - train
  - val
  - test
datatype_split:
- - 2000
  - 500
  - 500
delta_eta: 5.0
edge_cut: 0.5
emb_channels: 0
endcaps: true
factor: 0.3
hidden: 256
hidden_activation: ReLU
in_channels: 3
input_dir: $CFS/m3443/usr/daniel/dataset/filter_1
layernorm: true
log_dir: logging/version_1
lr: 0.0001
max_epochs: 25
n_graph_iters: 4
nb_edge_layer: 2
nb_node_layer: 5
noise: true
output_dir: $CFS/m3443/usr/daniel/dataset/gnn_1
overwrite: true
patience: 10
performance_path: stage_1.yaml
project: LRT_GNN
pt_background_min: 0.0
pt_signal_min: 0.0
regime:
- []
slack_alert: false
true_edges: layerless_true_edges
warmup: 200
weight: 2
