batch_size: 1
callbacks:
- GNNEffPur
- GNNBuilder
checkpoint_path: lightning_checkpoints
datatype_names:
- - train
  - val
  - test
datatype_split:
- - 900
  - 100
  - 500
delta_eta: 1.2
edge_cut: 0.5
emb_channels: 0
endcaps: true
factor: 0.3
hidden: 128
hidden_activation: ReLU
in_channels: 3
input_dir: $CFS/m3443/usr/daniel/dataset/filter_4
layernorm: true
log_dir: logging/version_4
lr: 0.001
max_epochs: 25
n_graph_iters: 8
nb_edge_layer: 8
nb_node_layer: 5
noise: true
output_dir: $CFS/m3443/usr/daniel/dataset/gnn_4
overwrite: true
patience: 10
performance_path: stage_4.yaml
project: LRT_GNN
pt_background_min: 0.0
pt_signal_min: 0.0
regime:
- []
slack_alert: false
true_edges: layerless_true_edges
warmup: 200
weight: 2
