stage_list:
    - { set: Embedding, name: LayerlessEmbedding, config: train.yaml,resume_id: , batch_config: configs/batch_gpu_default.yaml, batch_setup: True}
    - {set: Filter, name: VanillaFilter, config: train.yaml, resume_id: , batch_config: configs/batch_gpu_default.yaml,batch_setup: True}
    - {
      set: GNN,
      # ResAGNN, InteractionGNN or VanillaGCN 
      name: ResAGNN,
      config: train.yaml,
      resume_id: ,
      batch_config: configs/batch_gpu_default.yaml,
      batch_setup: True,
    }
